services:
  caddy:
    build:
      context: ./caddy
      dockerfile: Dockerfile
    environment:
      - CF_API_TOKEN=$CF_API_TOKEN
    container_name: caddy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - caddy_network

networks:
  caddy_network:

volumes:
  caddy_data:
  caddy_config:
