services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - caddy_network
    depends_on:
      - ntfy
      - gatus

  ntfy:
    image: binwiederhier/ntfy:latest
    command: serve
    volumes:
      - ntfy_data:/var/lib/ntfy
      - ./ntfy/server.yml:/etc/ntfy/server.yml
    ports:
      - 2010:2010
    networks:
      - caddy_network
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget -q --tries=1 http://localhost:2010/v1/health -O - | grep -Eo '\"healthy\"\\s*:\\s*true' || exit 1",
        ]
      interval: 300s
      timeout: 10s
      retries: 3
      start_period: 40s

  gatus:
    image: twinproduction/gatus:latest
    ports:
      - 8080:8080
    volumes:
      - gatus_data:/var/lib/gatus
      - ./gatus/config.yaml:/config/config.yaml
    environment:
      GATUS_NTFY_TOKEN: /run/secrets/gatus-ntfy-token
    networks:
      - caddy_network
    secrets:
      - gatus-ntfy-token

networks:
  caddy_network:

volumes:
  caddy_data:
  caddy_config:

  ntfy_data:
  gatus_data:

secrets:
  gatus-ntfy-token:
    file: etc/gatus/gatus-ntfy-token.txt
