services:
  gatus:
    image: twinproduction/gatus:latest
    container_name: gatus
    volumes:
      - gatus_data:/var/lib/gatus
      - ./config:/config
    environment:
      - GATUS_CONFIG_PATH=/config
    env_file:
      - /etc/gatus/gatus.env
    networks:
      - caddy

networks:
  caddy:
    external: true

volumes:
  gatus_data:
