storage:
  type: sqlite
  path: /var/lib/gatus/data.db

alerting:
  ntfy:
    topic: alerts
    url: https://ntfy.jayparry.dev
    priority: 4
    token: "${GATUS_NTFY_TOKEN}"
    default-alert:
      failure-threshold: 3
      send-on-resolved: true

endpoints:
  - name: portfolio
    group: web
    interval: 1m
    url: https://jayparry.dev
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: ntfy

  - name: bubblrs-ui
    group: web
    interval: 1m
    url: https://bubblrs.com/
    conditions:
      - "[STATUS] == any(200, 304)"
    alerts:
      - type: ntfy
